### ISSUE TITLE
Redis Clustering in Docker Swarm, Silo's wont find each other

### ISSUE THREAD

**Issue by NangiDev** [OrleansContrib/Orleans.Redis#18]
I'm having problem understand why my setup does not work.
I'm running a Redis with the membership table and I can see the silos register, but it only works with one silo. As soon as I add a second silo it never goes past 'Status:2'. It just reboots.

```
private static async Task<int> RunMainAsync()
{
    try
    {
        var host = new SiloHostBuilder()
            .ConfigureEndpoints(hostname: EnvVar.Hostname, siloPort: EnvVar.siloPort, gatewayPort: EnvVar.gatewayPort, listenOnAnyHostAddress: true)
            .AddRedisGrainStorageAsDefault(optionsBuilder => optionsBuilder.Configure(options =>
            {
                options.ConnectionString = "storage:6379";
                options.UseJson = true;
                options.DatabaseNumber = 1;
            }))
            .AddRedisGrainDirectory(
                "redis-directory-1",
                options => options.ConfigurationOptions = new ConfigurationOptions
                {
                    EndPoints = { { "storage:6379" } },
                    DefaultDatabase = 2
                })
            .UseRedisClustering(options =>
            {
                options.ConnectionString = "storage:6379";
                options.Database = 0;
            })
            .Configure<ClusterOptions>(options =>
            {
                options.ClusterId = EnvVar.ClusterId;
                options.ServiceId = EnvVar.ServiceId;
            })
            .ConfigureApplicationParts(parts =>
            {
                parts.AddFromApplicationBaseDirectory();
            })
            .ConfigureLogging(logging =>
            {
                logging.AddConsole();
            })
            .EnableDashboard()
        .Build();

        await host.StartAsync();

        await host.Stopped;
        Console.WriteLine("Stopping Silo host...");
        await host.StopAsync();
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
        return 1;
    }
    return 0;
}
```
This us my docker-compose.yaml
```
version: "3.8"

networks:
        orleans_swarm:
                driver: overlay

services:
        storage:
                image: redis:6.2.5
                ports:
                        - 6379:6379
                networks:
                        - orleans_swarm

        silo:
                image: localhost:5000/silo:latest
                deploy:
                        replicas: 1
                ports:
                        - 8080:8080 # Dashboard port
                        - 50051:50051 # Grpc port
                        - 20025:20025 # Gateway port
                        - 30025:30025 # Internal Silo port
                environment:
                        - GATEWAY_PORT=20025
                        - SILO_PORT=30025
                        - GRPC_PORT=50051
                        - USE_ORLEANS_DASHBOARD=true
                        - DASHBOARD_USERNAME=admin
                        - DASHBOARD_PASSWORD=nimda
                        - CLUSTER_ID=clusterId
                        - SERVICE_ID=serviceId
                networks:
                        - orleans_swarm
                depends_on:
                        - storage
```
And the error in the logs:
```
orleans_silo.2.i02fuoaksvrl@manager    | fail: Orleans.Messaging[100071]
orleans_silo.2.i02fuoaksvrl@manager    |       Failed to address message Request S10.0.0.109:30025:370887803*stg/TypeManager/00000011@S00000011->*grn/Orleans.Runtime.Versions.VersionStoreGrain/0+clusterId InvokeMethodRequest Orleans.Runtime.Versions.IVersionStoreGrain:GetSelectorStrategies #200 from activation [SystemTarget: S10.0.0.109:30025:370887803*stg/TypeManager/00000011@S00000011]
orleans_silo.2.i02fuoaksvrl@manager    |       Orleans.Runtime.OrleansException: TypeCode $331003096 not supported in the cluster
orleans_silo.2.i02fuoaksvrl@manager    |          at Orleans.Runtime.Catalog.GetCompatibleSilos(PlacementTarget target)
orleans_silo.2.i02fuoaksvrl@manager    |          at Orleans.Runtime.Placement.RandomPlacementDirector.OnAddActivation(PlacementStrategy strategy, PlacementTarget target, IPlacementContext context)
orleans_silo.2.i02fuoaksvrl@manager    |          at Orleans.Runtime.Placement.PlacementDirectorsManager.AddActivation(PlacementTarget target, IPlacementRuntime context, PlacementStrategy strategy)
orleans_silo.2.i02fuoaksvrl@manager    |          at Orleans.Runtime.Placement.PlacementDirectorsManager.SelectOrAddActivation(ActivationAddress sendingAddress, PlacementTarget targetGrain, IPlacementRuntime context, PlacementStrategy strategy)
orleans_silo.2.i02fuoaksvrl@manager    |          at Orleans.Runtime.Dispatcher.AddressMessageAsync(Message message, PlacementTarget target, PlacementStrategy strategy, ActivationAddress targetAddress)
orleans_silo.2.i02fuoaksvrl@manager    |          at Orleans.Runtime.Dispatcher.<>c__DisplayClass39_0.<<AsyncSendMessage>g__TransportMessageAferSending|0>d.MoveNext()
```
I've have noticed that the ip address it tries to connect to is the ingress ip provided by Docker Swarm and not my own overlay network 'orleans_swarm'

I've no idea if that makes any difference.

My node setup  is just three Ubuntu virtual machines, but for testing purposes I have drained the two nodes and only the manager is active.

Just to be clear my setup works perfect as long as I don't have more than one silo. It even works with more swarm nodes
